# Generated by Django 4.0 on 2022-05-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images-galerie/')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
