# Generated by Django 4.0 on 2022-05-14 20:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_newsletter_alter_actualite_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDuDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='profile-directeur/', verbose_name='Profil du directeur')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet du directeur')),
                ('message', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
