# Generated by Django 4.0 on 2022-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
