# Generated by Django 4.0 on 2022-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='newsLetter',
            field=models.BooleanField(default=False),
        ),
    ]
