# Generated by Django 4.0 on 2022-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0008_inscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='choix_cefa',
            field=models.CharField(max_length=250),
        ),
    ]
