# Generated by Django 4.0 on 2022-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0010_remove_contact_telephone_alter_inscription_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
